apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "selfhost-cloud.name" . }}-{{ .Values.name }}-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: traefik
  rules:
  - host: anud.ro
    http:
      paths:
      - path: /clock
        pathType: Prefix
        backend:
          service:
            name: {{ include "selfhost-cloud.name" . }}-{{ .Values.name }}-service
            port:
              number: 80
