apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "selfhost-cloud.name" . }}-{{ .Values.name }}-nginx-conf
  namespace: {{ .Values.global.namespace }}
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }
    }
