apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "selfhost-cloud.name" . }}-{{ .Values.name }}-httproute
  namespace: {{ .Values.global.namespace }}
spec:
  {{ $lb := index .Values "load-balancer" | default dict }}
  {{ $gwLocal := index .Values "gateway" | default dict }}
  {{ $gwParent := index $lb "gateway" | default dict }}
  {{ $name := default (index $gwParent "name") (index $gwLocal "name") }}
  {{ $namespace := default (index $gwParent "namespace") (index $gwLocal "namespace") }}
  {{ $section := default (index $gwParent "sectionName") (index $gwLocal "sectionName") }}
  {{ $hostnames := default (index $gwParent "hostnames") (index $gwLocal "hostnames") }}
  parentRefs:
  - name: traefik
    namespace: traefik

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "selfhost-cloud.name" . }}-{{ .Values.name }}
      port: 80
