apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "selfhost-cloud.name" . }}-httproute
  namespace: {{ .Values.global.namespace }}
spec:
  {{- $gwLocal := default dict (index .Values "gateway") }}
  {{- $lb := default dict (index $.Values "load-balancer") }}
  {{- $gwParent := default dict (index $lb "gateway") }}
  {{- $name := default (index $gwLocal "name") (index $gwParent "name") }}
  {{- $namespace := default (index $gwLocal "namespace") (index $gwParent "namespace") }}
  {{- $section := default (index $gwLocal "sectionName") (index $gwParent "sectionName") }}
  {{- $hostnames := default (index $gwLocal "hostnames") (index $gwParent "hostnames") }}
  parentRefs:
  - name: {{ $name }}
    namespace: {{ $namespace }}
    {{- if $section }}
    sectionName: {{ $section }}
    {{- end }}
  {{- if $hostnames }}
  hostnames:
  {{- range $hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /infrastructure/helm-deployer
    backendRefs:
    - name: {{ include "selfhost-cloud.name" . }}-service-external
      port: 80
