apiVersion: v1
kind: Namespace
metadata:
  name: public
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "selfhost-cloud"
    meta.helm.sh/release-namespace: "public"